# Generated by Django 5.1.2 on 2024-12-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_resetuuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
